version: '3'
services:
    app:
        build:
            context: .
        volumes:
            - .:/var/www/reg_form_php
        ports:
            - "8080:80"
        environment:
            XDEBUG_CONFIG: remote_host=host.docker.internal
            PHP_IDE_CONFIG: serverName=my-server
    web:
        image: nginx:alpine
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8000:80"
    db:
        image: mysql:8.0
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 12345678
